#
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]
all-features = true

[advisories]
unmaintained = 'workspace'
yanked = 'deny'
ignore = [
    { id = "RUSTSEC-2025-0141", reason = "bincode is unmaintained but it's currently not an issue, there are alternatives if we need to change" },
]

[bans]
deny = [
    { crate = "openssl-sys", use-instead = "rustls" },
    { crate = "openssl", use-instead = "rustls" },
    { crate = "aws-lc-sys", use-instead = "ring" },
    { crate = "cmake", use-instead = "cc" },
    # Ideally this is banned, but there are just far too many users of it :(
    # { crate = "chrono", use-instead = "time", wrappers = [
    #     "expect-json",
    #     "k8s-openapi",
    #     "kube-client",
    #     "kube-core",
    #     "kube-leader-election",
    #     #
    #     "postgres-types",
    #     "rusqlite",
    # ] },
]
multiple-versions = "deny"
skip = [
    { crate = "object@0.32.2", reason = "transitive dependency due to backtrace, backtrace is updated, but stable-eyre is using a feature that doesn't exist any longer, and can't update" },
    { crate = "miniz_oxide@0.7.4", reason = "pprof_util carries two different versions transitively" },
    { crate = "bitflags@1.3.2", reason = "corrosion again" },
    { crate = "itertools:<0.14", reason = "sigh" },
]
skip-tree = [
    { crate = "thiserror@1.0.69", reason = "many crates use this old version" },
    { crate = "hashbrown:<=0.16.1", reason = "we're at *5* different versions :p" },
    { crate = "rand:<0.10", reason = "another version of rand, meaning tons of old versions :p" },
    { crate = "sha2@0.10.9", reason = "old version that uses multiple other old crates" },
]

[[bans.features]]
name = "rustls"
deny = ["aws_lc_rs", "aws-lc-rs"]

[[bans.features]]
name = "tokio-rustls"
deny = ["aws-lc-rs"]

[[bans.features]]
name = "rustls-webpki"
deny = ["aws-lc-rs"]

[bans.workspace-dependencies]
unused = 'allow'

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = ["Apache-2.0", "MIT", "ISC", "BSD-2-Clause", "BSD-3-Clause", "Unicode-3.0"]
exceptions = [
    { crate = "adler32", allow = ["Zlib"] },
    { crate = "foldhash", allow = ["Zlib"] },
    # This license should not really be used for code, but here we are
    { crate = "notify", allow = ["CC0-1.0"] },
    { crate = "webpki-roots", allow = ["CDLA-Permissive-2.0"] },
    { crate = "foca", allow = ["MPL-2.0"] },
]

[[licenses.clarify]]
crate = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[sources.allow-org]
github = ["EmbarkStudios", "aya-rs"]
